# This is a basic workflow that is manually triggered

name: Index and ToC updater
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@regenerate'
          reaction: rocket
      - run: 'workflow ran successfully'
        if: steps.check.outputs.triggered == 'true'
